---
title: 'Conservation Siting of Offshore Wind Energy Development'
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
suppressPackageStartupMessages({
  library(flexdashboard) # devtools::install_github('rstudio/flexdashboard')
  library(raster)
  library(dplyr)
  library(leaflet)
  library(readr)
  library(ggplot2)
  library(plotly)
  library(RColorBrewer)
  library(DT)
})

# raster of utility values
r_u = raster(
  'data/utility/utility_birds-vs-industry8_v2_raster.grd')
# raster of ids
r_i = r_u
values(r_i) = 1:ncell(r_i)

# color palettes
pal = colorNumeric(
  brewer.pal(11, 'Spectral'), values(r_u), na.color='transparent')
pal_rev = colorNumeric(
  rev(brewer.pal(11, 'Spectral')), values(r_u), na.color='transparent')

# data frame of utility values
d_sum = read_csv('data/utility/utility_birds-vs-industry8_v2_data.csv') %>%
  select(
    rank,
    utility = u_avg,
    bird    = x,
    npv     = y,
    key     = i) %>%
  mutate(
    utility = round(utility, 3),
    bird    = round(bird, 3),
    npv     = round(npv, 3))

# Reactive that returns the whole dataset if there is no brush
d_sel = reactive({
  d = event_data('plotly_selected')
  if(is.null(d)){
    return(d_sum)
  } else {
    d_sum %>%
      semi_join(d, by='key')
  }
})

r_sel = reactive({
  d = event_data('plotly_selected')
  if(is.null(d)){
    return(r_u)
  } else {
    return(mask(r_u, raster::`%in%`(r_i, d$key), maskvalue=0))
  }
})
```

Column {data-width=650}
-----------------------------------------------------------------------

### Map of Average Utility

```{r map}
renderLeaflet({
  leaflet() %>%
    addProviderTiles('Stamen.TonerLite') %>%
    addRasterImage(r_u    , colors=pal, opacity=0.5, layerId='r_u') %>%
    addRasterImage(r_sel(), colors=pal, opacity=1  , layerId='r_sel') %>%
    addLegend('bottomright', pal=pal_rev, values=values(r_u),
      title = 'u', opacity = 1,
      labFormat = labelFormat(transform = function(x) rev(x)))
    
    #%>%
    #addDrawToolbar()
})
```

```{r}
# observe({
#   leafletProxy('map') %>%
#     removeImage('r_sel') %>%
#     addRasterImage(r_sel(), opacity=1, layerId='r_sel')
# })
```


Column {data-width=350}
-----------------------------------------------------------------------

### Plot of Operational Tradeoffs

```{r}
renderPlotly({
  
  key <- d_sum$key
  p = ggplot(d_sum, aes(bird, npv, colour=utility, key=key)) +
    geom_point() +
    coord_equal(xlim=c(0,1), ylim=c(0,1), expand=F) +
    scale_x_continuous(
      name = 'Bird Sensitivity', trans='reverse') +
    scale_y_continuous(
      name = 'Wind Profitablity ($NPV)') +
    scale_colour_gradientn(colours = brewer.pal(11, 'Spectral'), name='u') +
    geom_vline(xintercept = quantile(d_sum$bird, probs=(1-0.2), na.rm=T), linetype=2, col='red') +
    geom_vline(xintercept = quantile(d_sum$bird, probs=(1-0.6), na.rm=T), linetype=2, col='blue') +
    geom_hline(yintercept = quantile(d_sum$npv, probs=   0.2 , na.rm=T), linetype=2, col='red') +
    geom_hline(yintercept = quantile(d_sum$npv, probs=   0.6 , na.rm=T), linetype=2, col='blue')

  ggplotly(p) %>% layout(dragmode='select')   
})
```

### Table of Tradeoff Values

```{r}
renderDataTable({
    d_sel()
  })
```

